stages:
  - build
  - test
  - cleanup

before_script:
  - ssh-keyscan -H "servo.tssg.org" >> ~gitlab-runner/.ssh/known_hosts
  - git submodule sync # apply patch
  - echo "\nDone setting up repo\n"

build:
  stage: build
  tags: [mdb-sql-converter]
  script:
    - echo "Building image"
    - cd docker/ && make build
    - echo "Image build Complete"

unit_test_pass:
  stage: test
  tags: [mdb-sql-converter]
  script:
    - echo "Beginning tests for passing process"
    - cd docker/ && make test_pass
    - docker rm -f mdb_to_sql_converter
    - echo "Tests complete"

unit_test_fail:
  stage: test
  tags: [mdb-sql-converter]
  script:
    - echo "Beginning tests for failing process"
    - cd docker/ && make test_errors
    - echo "Tests complete"

cleanup:
  when: always
  stage: cleanup
  tags: [mdb-sql-converter]
  script:
    - cd docker/ && make destroy
    - cd docker/ && make remove
    - D=$(docker images -q -f "dangling=true")
    - if [ -n "$D" ]; then
    - docker rmi -f $D
    - fi
    - echo "Finished cleaning"
