stages:
  - build
  - deploy
  - cleanup

before_script:
  - ssh-keyscan -H "servo.tssg.org" >> ~gitlab-runner/.ssh/known_hosts
  - git submodule sync # apply patch
  - echo "\nDone setting up repo\n"

build:
  stage: build
  tags: [mdb-sql-converter]
  script:
    - echo "Building image"
    - cd docker/ && make build
    - echo "Image build Complete"

deploy:
  stage: deploy
  tags: [mdb-sql-converter]
  script:
    - echo "Deploying"
    - cd docker/ && make deploy
    - make deploy
    - echo "Deployment & Conversion Complete"

cleanup:
  when: always
  stage: cleanup
  tags: [mdb-sql-converter]
  script:
    - cd docker/ && make destroy
    - cd docker/ && make remove
    - D=$(docker images -q -f "dangling=true")
    - if [ -n "$D" ]; then
    - docker rmi -f $D
    - fi
    - echo "Finished cleaning"
